name = "elide-gradle"
main = "worker.ts"
compatibility_date = "2025-03-14"

routes = [
    { pattern = "gradle.elide.dev", custom_domain = true },
]

analytics_engine_datasets = [
    { binding = "ANALYTICS", dataset = "elide_gradle_v1" },
]

[observability.logs]
enabled = true
