name: "Job - Build"

"on":
  workflow_call:
    inputs:
      runner:
        description: "Runner to use for the job"
        required: false
        type: string
        default: "ubuntu-latest"
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner to use for the job"
        required: false
        default: "ubuntu-latest"

jobs:
  build:
    name: "Build"
    runs-on: ${{ inputs.runner || vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    permissions:
      contents: "read"
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: "Setup: Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: GraalVM (Java 24)"
        uses: graalvm/setup-graalvm@01ed653ac833fe80569f1ef9f25585ba2811baab # v1.3.3
        with:
          distribution: "graalvm"
          java-version: "24"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@a62ce5ca052e16ecd1c6eb3f2efde2e0228d5e80 # main
        with:
          version: latest
      - name: "Setup: Gradle"
        uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
        id: gradlebuild
        env:
          CI: true
        with:
          cache-disabled: true
      - name: "Setup: Dependencies (Example)"
        run: cd ./example-project && elide install
      - name: "Setup: Dependencies (Remote Example)"
        run: cd ./example-project-remote && elide install
      - name: "Build: Projects"
        run: ./gradlew --stacktrace --info --no-daemon build
      - name: "Build: Remote Example"
        run: cd ./example-project-remote && ../gradlew --stacktrace --info --no-daemon build
